pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                script {
                    sh 'mvn clean install'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    sh 'mvn test'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploy step (optional)'
            }
        }
    }

    post {
        success {
            echo 'Build and tests succeeded!'
        }

        failure {
            echo 'Build or tests failed!'
        }
    }
}
