pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                 git url: 'https://github.com/benjoyarackal/maven-webapp-.git', credentialsId: 'benjoyarackal'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}
